> Benjamin Nikholas

> Data Science / JCSDOL-014

> Modul 3 - Tugas 16

> 18 Juli 2024
---
---

In [91]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 30)
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

from sklearn.linear_model import Lasso
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

Gunakan melb_data.csv (Melbourne House Data) dengan: 
- Features: 'Suburb', 'Rooms', 'Type', 'Method', 'Distance', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Regionname' 
- Target: 'Price'

In [11]:
df_melb = pd.read_csv('melb_data.csv')
df_melb.info()
df_melb.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10199 entries, 0 to 10198
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         10199 non-null  object
 1   Address        10199 non-null  object
 2   Rooms          10199 non-null  int64
 3   Type           10199 non-null  object
 4   Price          10199 non-null  float64
 5   Method         10199 non-null  object
 6   SellerG        10199 non-null  object
 7   Date           10199 non-null  object
 8   Distance       10199 non-null  float64
 9   Postcode       10199 non-null  float64
 10  Bedroom2       10199 non-null  float64
 11  Bathroom       10199 non-null  float64
 12  Car            10199 non-null  float64
 13  Landsize       10199 non-null  float64
 14  BuildingArea   5426 non-null   float64
 15  YearBuilt      6260 non-null   float64
 16  CouncilArea    10198 non-null  object
 17  Lattitude      10198 non-null  float64
 18  Longtitude     10198 non-null  float64
 19  Regionname     10198 non-null  object
 20  Propertycount  10198 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 1.6+ MB

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [17]:
X = df_melb[['Suburb', 'Rooms', 'Type', 'Method', 'Distance', 
             'Bedroom2', 'Bathroom', 'Car', 'Landsize', 
             'BuildingArea', 'YearBuilt', 'CouncilArea', 'Regionname']]
y = df_melb['Price']

Lakukan EDA secara sederhana untuk eksplorasi dataset.

In [28]:
X.describe(include = ['int', 'float'])

,Rooms,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt
count,10199.000000,10199.000000,10199.000000,10199.000000,10199.000000,10199.000000,5426.000000,6260.00000
mean,2.865575,9.072939,2.834690,1.505246,1.549073,486.953133,144.439610,1962.75607
std,0.956532,4.582092,0.967367,0.690441,0.942513,1302.065000,140.242328,38.25873
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.00000
25%,2.000000,5.900000,2.000000,1.000000,1.000000,150.000000,90.000000,1940.00000
50%,3.000000,8.800000,3.000000,1.000000,1.000000,370.000000,123.000000,1970.00000
75%,3.000000,11.800000,3.000000,2.000000,2.000000,631.000000,170.000000,1999.00000
max,8.000000,47.400000,20.000000,8.000000,10.000000,75100.000000,6791.000000,2018.00000

In [29]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10199 entries, 0 to 10198
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Suburb        10199 non-null  object
 1   Rooms         10199 non-null  int64
 2   Type          10199 non-null  object
 3   Method        10199 non-null  object
 4   Distance      10199 non-null  float64
 5   Bedroom2      10199 non-null  float64
 6   Bathroom      10199 non-null  float64
 7   Car           10199 non-null  float64
 8   Landsize      10199 non-null  float64
 9   BuildingArea  5426 non-null   float64
 10  YearBuilt     6260 non-null   float64
 11  CouncilArea   10198 non-null  object
 12  Regionname    10198 non-null  object
dtypes: float64(7), int64(1), object(5)
memory usage: 1.0+ MB

Splitting dataset dengan proporsi 80:20 dan random_state = 2020

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 2020)

Gunakan ColumnTransformer untuk imputasi missing value dan encoding. 
- Ada 4 features yang mengandung missing value. Isi missing value tersebut 
dengan imputer yang menurut kamu paling sesuai dengan karakter masing-masing 
feature. 
- Ada 5 features categorical. Lakukan encoding pada features tersebut sesuai 
dengan karakter masing-masing feature.

In [37]:
num_features = X.select_dtypes(['int', 'float']).columns.to_list()
categorical_features =  X.select_dtypes(['object']).columns.to_list()

# num_transformer =

In [41]:
# Check if the numerical features is discrete or continues
# if continue use mean, elif discrete use median

for i in num_features:
    print(i, X[i].value_counts().to_list())

Rooms [4277, 3059, 1812, 576, 416, 46, 7, 6]
Distance [681, 367, 324, 287, 252, 248, 235, 229, 214, 208, 192, 187, 185, 180, 154, 153, 153, 150, 150, 147, 145, 141, 141, 137, 132, 125, 124, 120, 119, 118, 110, 110, 108, 102, 101, 97, 95, 94, 90, 90, 89, 87, 83, 83, 78, 68, 67, 65, 65, 64, 63, 62, 60, 58, 58, 57, 56, 56, 54, 53, 52, 52, 52, 50, 48, 47, 43, 43, 42, 42, 41, 40, 39, 39, 38, 37, 36, 36, 36, 35, 33, 32, 31, 30, 29, 28, 27, 26, 26, 26, 22, 22, 21, 21, 21, 21, 19, 19, 19, 18, 17, 17, 16, 16, 15, 15, 15, 14, 14, 13, 13, 12, 12, 12, 11, 11, 11, 11, 11, 10, 10, 10, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Bedroom2 [4295, 3147, 1722, 587, 377, 42, 15, 7, 3, 3, 1]
Bathroom [5908, 3483, 668, 82, 31, 20, 4, 2, 1]
Car [4466, 3940, 842, 511, 353, 40, 32, 7, 6, 1, 1]
Landsize [1740, 65, 40, 34, 29, 28, 28, 28, 27, 26, 25, 24, 24, 24, 23, 23, 23, 22, 21, 21, 21, 20, 20, 20, 20, 20, 20, 20, 20, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 18, 18, 18, 18, 18, 18, 18, 18, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
BuildingArea [92, 68, 63, 60, 60, 57, 55, 55, 55, 50, 50, 49, 47, 47, 46, 45, 45, 45, 44, 44, 44, 44, 43, 42, 42, 42, 41, 40, 39, 38, 36, 36, 36, 36, 35, 35, 34, 34, 34, 34, 34, 33, 33, 33, 32, 32, 32, 32, 32, 32, 32, 31, 31, 31, 31, 31, 31, 30, 30, 30, 30, 29, 29, 29, 29, 28, 28, 28, 28, 27, 27, 27, 26, 26, 26, 26, 26, 25, 25, 25, 25, 24, 24, 24, 24, 24, 23, 23, 23, 23, 22, 22, 22, 22, 22, 22, 21, 21, 21, 21, 21, 21, 21, 20, 20, 20, 19, 19, 19, 19, 19, 19, 19, 18, 18, 18, 18, 18, 17, 17, 17, 17, 16, 16, 16, 16, 16, 15, 15, 15, 15, 15, 15, 15, 15, 15, 14, 14, 14, 14, 14, 14, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 12, 12, 12, 12, 12, 11, 11, 11, 11, 11, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
YearBuilt [683, 533, 460, 290, 234, 228, 225, 205, 199, 197, 191, 142, 139, 137, 131, 116, 113, 112, 89, 88, 83, 82, 78, 76, 74, 71, 70, 61, 59, 58, 56, 51, 50, 49, 47, 47, 44, 43, 43, 40, 25, 25, 23, 20, 19, 19, 16, 15, 14, 14, 14, 14, 12, 12, 12, 11, 11, 10, 10, 9, 9, 9, 8, 8, 8, 7, 7, 7, 7, 7, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [44]:
# Transformer

num_transformer = SimpleImputer(strategy = 'mean')

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy = 'most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown = 'ignore'))
])

# Col Transformer

preprocessor = ColumnTransformer(transformers = [
    ('num', num_transformer, num_features),
    ('cat', categorical_transformer, categorical_features)
])

In [47]:
# Fit dan transform data train and test

X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

In [52]:
print(X_train_processed.toarray())
print(preprocessor.get_feature_names_out())

[[ 1.   2.8  1.  ...  0.   0.   0. ]
 [ 4.   3.5  4.  ...  1.   0.   0. ]
 [ 3.  13.1  3.  ...  0.   0.   0. ]
 ...
 [ 2.  13.9  2.  ...  0.   0.   0. ]
 [ 4.   9.2  4.  ...  1.   0.   0. ]
 [ 2.   5.2  2.  ...  0.   0.   0. ]]
['num__Rooms' 'num__Distance' 'num__Bedroom2' 'num__Bathroom' 'num__Car'
 'num__Landsize' 'num__BuildingArea' 'num__YearBuilt'
 'cat__Suburb_Abbotsford' 'cat__Suburb_Aberfeldie'
 'cat__Suburb_Airport West' 'cat__Suburb_Albanvale'
 'cat__Suburb_Albert Park' 'cat__Suburb_Albion' 'cat__Suburb_Alphington'
 'cat__Suburb_Altona' 'cat__Suburb_Altona Meadows'
 'cat__Suburb_Altona North' 'cat__Suburb_Armadale'
 'cat__Suburb_Ascot Vale' 'cat__Suburb_Ashburton' 'cat__Suburb_Ashwood'
 'cat__Suburb_Aspendale' 'cat__Suburb_Avondale Heights'
 'cat__Suburb_Balaclava' 'cat__Suburb_Balwyn' 'cat__Suburb_Balwyn North'
 'cat__Suburb_Bayswater' 'cat__Suburb_Bayswater North'
 'cat__Suburb_Beaumaris' 'cat__Suburb_Bellfield' 'cat__Suburb_Bentleigh'
 'cat__Suburb_Bentleigh East' 'cat__Suburb_Berwick'
 'cat__Suburb_Black Rock' 'cat__Suburb_Blackburn'
 'cat__Suburb_Blackburn North' 'cat__Suburb_Blackburn South'
 'cat__Suburb_Bonbeach' 'cat__Suburb_Boronia' 'cat__Suburb_Box Hill'
 'cat__Suburb_Braybrook' 'cat__Suburb_Briar Hill' 'cat__Suburb_Brighton'
 'cat__Suburb_Brighton East' 'cat__Suburb_Broadmeadows'
 'cat__Suburb_Brooklyn' 'cat__Suburb_Brunswick'
 'cat__Suburb_Brunswick East' 'cat__Suburb_Brunswick West'
 'cat__Suburb_Bulleen' 'cat__Suburb_Bundoora' 'cat__Suburb_Burnley'
 'cat__Suburb_Burnside Heights' 'cat__Suburb_Burwood'
 'cat__Suburb_Burwood East' 'cat__Suburb_Cairnlea'
 'cat__Suburb_Camberwell' 'cat__Suburb_Campbellfield'
 'cat__Suburb_Canterbury' 'cat__Suburb_Carlton'
 'cat__Suburb_Carlton North' 'cat__Suburb_Carnegie'
 'cat__Suburb_Caroline Springs' 'cat__Suburb_Carrum'
 'cat__Suburb_Carrum Downs' 'cat__Suburb_Caulfield'
 'cat__Suburb_Caulfield East' 'cat__Suburb_Caulfield North'
 'cat__Suburb_Caulfield South' 'cat__Suburb_Chadstone'
 'cat__Suburb_Chelsea' 'cat__Suburb_Chelsea Heights'
 'cat__Suburb_Cheltenham' 'cat__Suburb_Clayton' 'cat__Suburb_Clifton Hill'
 'cat__Suburb_Coburg' 'cat__Suburb_Coburg North' 'cat__Suburb_Collingwood'
 'cat__Suburb_Craigieburn' 'cat__Suburb_Cranbourne' 'cat__Suburb_Cremorne'
 'cat__Suburb_Croydon' 'cat__Suburb_Croydon North' 'cat__Suburb_Dallas'
 'cat__Suburb_Dandenong' 'cat__Suburb_Dandenong North'
 'cat__Suburb_Deer Park' 'cat__Suburb_Diamond Creek'
 'cat__Suburb_Dingley Village' 'cat__Suburb_Docklands'
 'cat__Suburb_Doncaster' 'cat__Suburb_Doncaster East'
 'cat__Suburb_Donvale' 'cat__Suburb_Doreen' 'cat__Suburb_Doveton'
 'cat__Suburb_Eaglemont' 'cat__Suburb_East Melbourne'
 'cat__Suburb_Elsternwick' 'cat__Suburb_Eltham' 'cat__Suburb_Eltham North'
 'cat__Suburb_Elwood' 'cat__Suburb_Epping' 'cat__Suburb_Essendon'
 'cat__Suburb_Essendon North' 'cat__Suburb_Essendon West'
 'cat__Suburb_Fairfield' 'cat__Suburb_Fawkner'
 'cat__Suburb_Ferntree Gully' 'cat__Suburb_Fitzroy'
 'cat__Suburb_Fitzroy North' 'cat__Suburb_Flemington'
 'cat__Suburb_Footscray' 'cat__Suburb_Forest Hill' 'cat__Suburb_Frankston'
 'cat__Suburb_Frankston North' 'cat__Suburb_Frankston South'
 'cat__Suburb_Gardenvale' 'cat__Suburb_Gisborne'
 'cat__Suburb_Gladstone Park' 'cat__Suburb_Glen Huntly'
 'cat__Suburb_Glen Iris' 'cat__Suburb_Glen Waverley' 'cat__Suburb_Glenroy'
 'cat__Suburb_Gowanbrae' 'cat__Suburb_Greensborough'
 'cat__Suburb_Greenvale' 'cat__Suburb_Hadfield' 'cat__Suburb_Hallam'
 'cat__Suburb_Hampton' 'cat__Suburb_Hampton East' 'cat__Suburb_Hawthorn'
 'cat__Suburb_Hawthorn East' 'cat__Suburb_Heathmont'
 'cat__Suburb_Heidelberg' 'cat__Suburb_Heidelberg Heights'
 'cat__Suburb_Heidelberg West' 'cat__Suburb_Highett'
 'cat__Suburb_Hillside' 'cat__Suburb_Hoppers Crossing'
 'cat__Suburb_Hughesdale' 'cat__Suburb_Huntingdale' 'cat__Suburb_Ivanhoe'
 'cat__Suburb_Ivanhoe East' 'cat__Suburb_Jacana' 'cat__Suburb_Kealba'
 'cat__Suburb_Keilor Downs' 'cat__Suburb_Keilor East'
 'cat__Suburb_Keilor Park' 'cat__Suburb_Kensington' 'cat__Suburb_Kew'
 'cat__Suburb_Kew East' 'cat__Suburb_Keysborough' 'cat__Suburb_Kings Park'
 'cat__Suburb_Kingsbury' 'cat__Suburb_Kingsville' 'cat__Suburb_Kooyong'
 'cat__Suburb_Lalor' 'cat__Suburb_Langwarrin' 'cat__Suburb_Maidstone'
 'cat__Suburb_Malvern' 'cat__Suburb_Malvern East'
 'cat__Suburb_Maribyrnong' 'cat__Suburb_Meadow Heights'
 'cat__Suburb_Melbourne' 'cat__Suburb_Melton' 'cat__Suburb_Melton South'
 'cat__Suburb_Melton West' 'cat__Suburb_Mentone' 'cat__Suburb_Mernda'
 'cat__Suburb_Middle Park' 'cat__Suburb_Mill Park' 'cat__Suburb_Mitcham'
 'cat__Suburb_Mont Albert' 'cat__Suburb_Montmorency'
 'cat__Suburb_Moonee Ponds' 'cat__Suburb_Moorabbin'
 'cat__Suburb_Mooroolbark' 'cat__Suburb_Mordialloc'
 'cat__Suburb_Mount Waverley' 'cat__Suburb_Mulgrave'
 'cat__Suburb_Murrumbeena' 'cat__Suburb_Narre Warren'
 'cat__Suburb_Newport' 'cat__Suburb_Niddrie' 'cat__Suburb_Noble Park'
 'cat__Suburb_North Melbourne' 'cat__Suburb_Northcote'
 'cat__Suburb_Notting Hill' 'cat__Suburb_Nunawading'
 'cat__Suburb_Oak Park' 'cat__Suburb_Oakleigh' 'cat__Suburb_Oakleigh East'
 'cat__Suburb_Oakleigh South' 'cat__Suburb_Ormond' 'cat__Suburb_Parkdale'
 'cat__Suburb_Parkville' 'cat__Suburb_Pascoe Vale'
 'cat__Suburb_Point Cook' 'cat__Suburb_Port Melbourne'
 'cat__Suburb_Prahran' 'cat__Suburb_Preston' 'cat__Suburb_Princes Hill'
 'cat__Suburb_Reservoir' 'cat__Suburb_Richmond'
 'cat__Suburb_Riddells Creek' 'cat__Suburb_Ringwood'
 'cat__Suburb_Ringwood East' 'cat__Suburb_Ringwood North'
 'cat__Suburb_Ripponlea' 'cat__Suburb_Rockbank' 'cat__Suburb_Rosanna'
 'cat__Suburb_Rowville' 'cat__Suburb_Roxburgh Park'
 'cat__Suburb_Sandhurst' 'cat__Suburb_Sandringham' 'cat__Suburb_Scoresby'
 'cat__Suburb_Seabrook' 'cat__Suburb_Seaford' 'cat__Suburb_Seaholme'
 'cat__Suburb_Seddon' 'cat__Suburb_Silvan' 'cat__Suburb_Skye'
 'cat__Suburb_South Kingsville' 'cat__Suburb_South Melbourne'
 'cat__Suburb_South Morang' 'cat__Suburb_South Yarra'
 'cat__Suburb_Southbank' 'cat__Suburb_Spotswood' 'cat__Suburb_Springvale'
 'cat__Suburb_St Albans' 'cat__Suburb_St Kilda' 'cat__Suburb_Strathmore'
 'cat__Suburb_Strathmore Heights' 'cat__Suburb_Sunbury'
 'cat__Suburb_Sunshine' 'cat__Suburb_Sunshine North'
 'cat__Suburb_Sunshine West' 'cat__Suburb_Surrey Hills'
 'cat__Suburb_Sydenham' 'cat__Suburb_Tarneit' 'cat__Suburb_Taylors Hill'
 'cat__Suburb_Taylors Lakes' 'cat__Suburb_Templestowe'
 'cat__Suburb_Templestowe Lower' 'cat__Suburb_The Basin'
 'cat__Suburb_Thomastown' 'cat__Suburb_Thornbury' 'cat__Suburb_Toorak'
 'cat__Suburb_Travancore' 'cat__Suburb_Truganina'
 'cat__Suburb_Tullamarine' 'cat__Suburb_Vermont'
 'cat__Suburb_Vermont South' 'cat__Suburb_Viewbank' 'cat__Suburb_Wantirna'
 'cat__Suburb_Wantirna South' 'cat__Suburb_Warrandyte'
 'cat__Suburb_Watsonia' 'cat__Suburb_Werribee'
 'cat__Suburb_West Footscray' 'cat__Suburb_West Melbourne'
 'cat__Suburb_Westmeadows' 'cat__Suburb_Wheelers Hill'
 'cat__Suburb_Williams Landing' 'cat__Suburb_Williamstown'
 'cat__Suburb_Williamstown North' 'cat__Suburb_Windsor'
 'cat__Suburb_Wyndham Vale' 'cat__Suburb_Yallambie'
 'cat__Suburb_Yarraville' 'cat__Type_h' 'cat__Type_t' 'cat__Type_u'
 'cat__Method_PI' 'cat__Method_S' 'cat__Method_SA' 'cat__Method_SP'
 'cat__Method_VB' 'cat__CouncilArea_Banyule' 'cat__CouncilArea_Bayside'
 'cat__CouncilArea_Boroondara' 'cat__CouncilArea_Brimbank'
 'cat__CouncilArea_Casey' 'cat__CouncilArea_Darebin'
 'cat__CouncilArea_Frankston' 'cat__CouncilArea_Glen Eira'
 'cat__CouncilArea_Greater Dandenong' 'cat__CouncilArea_Hobsons Bay'
 'cat__CouncilArea_Hume' 'cat__CouncilArea_K' 'cat__CouncilArea_Kingston'
 'cat__CouncilArea_Knox' 'cat__CouncilArea_Macedon Ranges'
 'cat__CouncilArea_Manningham' 'cat__CouncilArea_Maribyrnong'
 'cat__CouncilArea_Maroondah' 'cat__CouncilArea_Melbourne'
 'cat__CouncilArea_Melton' 'cat__CouncilArea_Monash'
 'cat__CouncilArea_Moonee Valley' 'cat__CouncilArea_Moreland'
 'cat__CouncilArea_Nillumbik' 'cat__CouncilArea_Port Phillip'
 'cat__CouncilArea_Stonnington' 'cat__CouncilArea_Unavailable'
 'cat__CouncilArea_Whitehorse' 'cat__CouncilArea_Whittlesea'
 'cat__CouncilArea_Wyndham' 'cat__CouncilArea_Yarra'
 'cat__CouncilArea_Yarra Ranges' 'cat__Regionname_Eastern Metropolitan'
 'cat__Regionname_Eastern Victoria'
 'cat__Regionname_Northern Metropolitan'
 'cat__Regionname_Northern Victoria'
 'cat__Regionname_South-Eastern Metropolitan'
 'cat__Regionname_Southern Metropolitan'
 'cat__Regionname_Western Metropolitan' 'cat__Regionname_Western Victoria']

In [62]:
X_train_transform = pd.DataFrame(X_train_processed.toarray(), columns = preprocessor.get_feature_names_out())
X_test_transform = pd.DataFrame(X_test_processed.toarray(), columns = preprocessor.get_feature_names_out())

In [86]:
# Check if there is any null values after transform

print(f'Train Data Check:\n{X_train_transform.isna().sum().sort_values(ascending = False)[:5]}')
print('--'*15)
print(f'Test Data Check:\n{X_test_transform.isna().sum().sort_values(ascending = False)[:5]}')

Train Data Check:
num__Rooms                 0
cat__Suburb_Rockbank       0
cat__Suburb_Seabrook       0
cat__Suburb_Scoresby       0
cat__Suburb_Sandringham    0
dtype: int64
------------------------------
Test Data Check:
num__Rooms                 0
cat__Suburb_Rockbank       0
cat__Suburb_Seabrook       0
cat__Suburb_Scoresby       0
cat__Suburb_Sandringham    0
dtype: int64

Lakukan Scaling pada numerical features. Pilih scaler yang menurut kamu paling sesuai berdasarkan karakteristik datanya.

In [88]:
scaler = StandardScaler(with_mean = True)  

X_train_transform_scaled = scaler.fit_transform(X_train_transform)
X_test_transform_scaled = scaler.transform(X_test_transform)

Lakukan prediksi dengan metode Lasso pada data preprocessed.

In [103]:
lasso_model = Lasso()

lasso_model.fit(X_train_transform_scaled, y_train)

y_train_pred = lasso_model.predict(X_train_transform_scaled)
y_test_pred = lasso_model.predict(X_test_transform_scaled)

C:\Users\benjamin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.588e+14, tolerance: 3.265e+11
  model = cd_fast.enet_coordinate_descent(

TINGGAL BIKIN EVALUASI