In [ ]:
## Text Mining ==> Proses Ekstraksi Informasi dari suatu Dokumen
Feature Extraction

Makan, dimakan, memakan, termakan ==> Makan

connect, connecting, connection, connected ==> connect
Sing, Sang, Singer ==> sing

Encoding ==> Embedding

"Hari ini, saya makan baso cuankie harganya 15000, mahal juga ya" ==> proses pemotongan kalimat menjadi kata ==> Tokenization

Saya, saya, SAYA ==> dianggap berbeda

Jakarta, JAKARTA, jakarta ==> one hot encoding

Data Preprocessing pada Text
1. Text Normalization ==> menyamakan text ==> Lowercase
2. Remove Punctuation ==> hapus tanda baca
3. Remove stopwords ==> Kata yg sering dipake tapi tidak memiliki arti
4. Stemming ==> Proses normalization text dg menghilangkan Imbuhan ==> yg sering digunakan untuk bahasa Indo, package ==> sastrawi, Spacy
5. Lemmatization ==> Proses normalization text dg mengembalikan kata ke bentuk dasarnya
6. Tokenization ==> Proses pemotongan kalimat menjadi kata
7. Vectorization ==> Mengubah kata yg sudah dipotong dan dibersihkan menjadi Angka
8. Klasifikasi - ML kaya biasa

Package yg umum digunakan untuk handling text ==> NLTK ==> Natural Language Toolkit
Proses keseluruhan ==> NLP ==> Natural Language Processing




ANJING KAU!!!!!!

anjing kau

anjing juga kau ya :)

In [1]:
import nltk

In [2]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\23522\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [3]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\23522\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [4]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from string import punctuation

In [9]:
text = "Halo, selamat malam. Nama Saya Andre. Saat ini saya sedang makan mie ayam harganya rp 25.000. Anda mau?"
text

'Halo, selamat malam. Nama Saya Andre. Saat ini saya sedang makan mie ayam harganya rp 25.000. Anda mau?'

## Normalization

In [10]:
text = text.lower()
text

'halo, selamat malam. nama saya andre. saat ini saya sedang makan mie ayam harganya rp 25.000. anda mau?'

## Tokenize

In [11]:
sent_tokenize(text)

['halo, selamat malam.',
 'nama saya andre.',
 'saat ini saya sedang makan mie ayam harganya rp 25.000. anda mau?']

In [12]:
word_tokenize(text)

['halo',
 ',',
 'selamat',
 'malam',
 '.',
 'nama',
 'saya',
 'andre',
 '.',
 'saat',
 'ini',
 'saya',
 'sedang',
 'makan',
 'mie',
 'ayam',
 'harganya',
 'rp',
 '25.000.',
 'anda',
 'mau',
 '?']

In [13]:
tokens = word_tokenize(text)

In [14]:
tokens

['halo',
 ',',
 'selamat',
 'malam',
 '.',
 'nama',
 'saya',
 'andre',
 '.',
 'saat',
 'ini',
 'saya',
 'sedang',
 'makan',
 'mie',
 'ayam',
 'harganya',
 'rp',
 '25.000.',
 'anda',
 'mau',
 '?']

## Punctuation Removal

In [16]:
punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [17]:
result = []
for i in tokens:
    if i not in punctuation:
        result.append(i)
result

['halo',
 'selamat',
 'malam',
 'nama',
 'saya',
 'andre',
 'saat',
 'ini',
 'saya',
 'sedang',
 'makan',
 'mie',
 'ayam',
 'harganya',
 'rp',
 '25.000.',
 'anda',
 'mau']

In [18]:
result2 = [i for i in tokens if i not in punctuation]

In [20]:
result2

['halo',
 'selamat',
 'malam',
 'nama',
 'saya',
 'andre',
 'saat',
 'ini',
 'saya',
 'sedang',
 'makan',
 'mie',
 'ayam',
 'harganya',
 'rp',
 '25.000.',
 'anda',
 'mau']

## Alpha Numeric Cleansing

In [21]:
tokens2 = [i for i in tokens if i.isalnum()]

In [22]:
tokens2

['halo',
 'selamat',
 'malam',
 'nama',
 'saya',
 'andre',
 'saat',
 'ini',
 'saya',
 'sedang',
 'makan',
 'mie',
 'ayam',
 'harganya',
 'rp',
 'anda',
 'mau']

## Stopwords Removal

In [23]:
stopwords.words('indonesian')

['ada',
 'adalah',
 'adanya',
 'adapun',
 'agak',
 'agaknya',
 'agar',
 'akan',
 'akankah',
 'akhir',
 'akhiri',
 'akhirnya',
 'aku',
 'akulah',
 'amat',
 'amatlah',
 'anda',
 'andalah',
 'antar',
 'antara',
 'antaranya',
 'apa',
 'apaan',
 'apabila',
 'apakah',
 'apalagi',
 'apatah',
 'artinya',
 'asal',
 'asalkan',
 'atas',
 'atau',
 'ataukah',
 'ataupun',
 'awal',
 'awalnya',
 'bagai',
 'bagaikan',
 'bagaimana',
 'bagaimanakah',
 'bagaimanapun',
 'bagi',
 'bagian',
 'bahkan',
 'bahwa',
 'bahwasanya',
 'baik',
 'bakal',
 'bakalan',
 'balik',
 'banyak',
 'bapak',
 'baru',
 'bawah',
 'beberapa',
 'begini',
 'beginian',
 'beginikah',
 'beginilah',
 'begitu',
 'begitukah',
 'begitulah',
 'begitupun',
 'bekerja',
 'belakang',
 'belakangan',
 'belum',
 'belumlah',
 'benar',
 'benarkah',
 'benarlah',
 'berada',
 'berakhir',
 'berakhirlah',
 'berakhirnya',
 'berapa',
 'berapakah',
 'berapalah',
 'berapapun',
 'berarti',
 'berawal',
 'berbagai',
 'berdatangan',
 'beri',
 'berikan',
 'berikut',
 'berikutnya',
 'berjumlah',
 'berkali-kali',
 'berkata',
 'berkehendak',
 'berkeinginan',
 'berkenaan',
 'berlainan',
 'berlalu',
 'berlangsung',
 'berlebihan',
 'bermacam',
 'bermacam-macam',
 'bermaksud',
 'bermula',
 'bersama',
 'bersama-sama',
 'bersiap',
 'bersiap-siap',
 'bertanya',
 'bertanya-tanya',
 'berturut',
 'berturut-turut',
 'bertutur',
 'berujar',
 'berupa',
 'besar',
 'betul',
 'betulkah',
 'biasa',
 'biasanya',
 'bila',
 'bilakah',
 'bisa',
 'bisakah',
 'boleh',
 'bolehkah',
 'bolehlah',
 'buat',
 'bukan',
 'bukankah',
 'bukanlah',
 'bukannya',
 'bulan',
 'bung',
 'cara',
 'caranya',
 'cukup',
 'cukupkah',
 'cukuplah',
 'cuma',
 'dahulu',
 'dalam',
 'dan',
 'dapat',
 'dari',
 'daripada',
 'datang',
 'dekat',
 'demi',
 'demikian',
 'demikianlah',
 'dengan',
 'depan',
 'di',
 'dia',
 'diakhiri',
 'diakhirinya',
 'dialah',
 'diantara',
 'diantaranya',
 'diberi',
 'diberikan',
 'diberikannya',
 'dibuat',
 'dibuatnya',
 'didapat',
 'didatangkan',
 'digunakan',
 'diibaratkan',
 'diibaratkannya',
 'diingat',
 'diingatkan',
 'diinginkan',
 'dijawab',
 'dijelaskan',
 'dijelaskannya',
 'dikarenakan',
 'dikatakan',
 'dikatakannya',
 'dikerjakan',
 'diketahui',
 'diketahuinya',
 'dikira',
 'dilakukan',
 'dilalui',
 'dilihat',
 'dimaksud',
 'dimaksudkan',
 'dimaksudkannya',
 'dimaksudnya',
 'diminta',
 'dimintai',
 'dimisalkan',
 'dimulai',
 'dimulailah',
 'dimulainya',
 'dimungkinkan',
 'dini',
 'dipastikan',
 'diperbuat',
 'diperbuatnya',
 'dipergunakan',
 'diperkirakan',
 'diperlihatkan',
 'diperlukan',
 'diperlukannya',
 'dipersoalkan',
 'dipertanyakan',
 'dipunyai',
 'diri',
 'dirinya',
 'disampaikan',
 'disebut',
 'disebutkan',
 'disebutkannya',
 'disini',
 'disinilah',
 'ditambahkan',
 'ditandaskan',
 'ditanya',
 'ditanyai',
 'ditanyakan',
 'ditegaskan',
 'ditujukan',
 'ditunjuk',
 'ditunjuki',
 'ditunjukkan',
 'ditunjukkannya',
 'ditunjuknya',
 'dituturkan',
 'dituturkannya',
 'diucapkan',
 'diucapkannya',
 'diungkapkan',
 'dong',
 'dua',
 'dulu',
 'empat',
 'enggak',
 'enggaknya',
 'entah',
 'entahlah',
 'guna',
 'gunakan',
 'hal',
 'hampir',
 'hanya',
 'hanyalah',
 'hari',
 'harus',
 'haruslah',
 'harusnya',
 'hendak',
 'hendaklah',
 'hendaknya',
 'hingga',
 'ia',
 'ialah',
 'ibarat',
 'ibaratkan',
 'ibaratnya',
 'ibu',
 'ikut',
 'ingat',
 'ingat-ingat',
 'ingin',
 'inginkah',
 'inginkan',
 'ini',
 'inikah',
 'inilah',
 'itu',
 'itukah',
 'itulah',
 'jadi',
 'jadilah',
 'jadinya',
 'jangan',
 'jangankan',
 'janganlah',
 'jauh',
 'jawab',
 'jawaban',
 'jawabnya',
 'jelas',
 'jelaskan',
 'jelaslah',
 'jelasnya',
 'jika',
 'jikalau',
 'juga',
 'jumlah',
 'jumlahnya',
 'justru',
 'kala',
 'kalau',
 'kalaulah',
 'kalaupun',
 'kalian',
 'kami',
 'kamilah',
 'kamu',
 'kamulah',
 'kan',
 'kapan',
 'kapankah',
 'kapanpun',
 'karena',
 'karenanya',
 'kasus',
 'kata',
 'katakan',
 'katakanlah',
 'katanya',
 'ke',
 'keadaan',
 'kebetulan',
 'kecil',
 'kedua',
 'keduanya',
 'keinginan',
 'kelamaan',
 'kelihatan',
 'kelihatannya',
 'kelima',
 'keluar',
 'kembali',
 'kemudian',
 'kemungkinan',
 'kemungkinannya',
 'kenapa',
 'kepada',
 'kepadanya',
 'kesampaian',
 'keseluruhan',
 'keseluruhannya',
 'keterlaluan',
 'ketika',
 'khususnya',
 'kini',
 'kinilah',
 'kira',
 'kira-kira',
 'kiranya',
 'kita',
 'kitalah',
 'kok',
 'kurang',
 'lagi',
 'lagian',
 'lah',
 'lain',
 'lainnya',
 'lalu',
 'lama',
 'lamanya',
 'lanjut',
 'lanjutnya',
 'lebih',
 'lewat',
 'lima',
 'luar',
 'macam',
 'maka',
 'makanya',
 'makin',
 'malah',
 'malahan',
 'mampu',
 'mampukah',
 'mana',
 'manakala',
 'manalagi',
 'masa',
 'masalah',
 'masalahnya',
 'masih',
 'masihkah',
 'masing',
 'masing-masing',
 'mau',
 'maupun',
 'melainkan',
 'melakukan',
 'melalui',
 'melihat',
 'melihatnya',
 'memang',
 'memastikan',
 'memberi',
 'memberikan',
 'membuat',
 'memerlukan',
 'memihak',
 'meminta',
 'memintakan',
 'memisalkan',
 'memperbuat',
 'mempergunakan',
 'memperkirakan',
 'memperlihatkan',
 'mempersiapkan',
 'mempersoalkan',
 'mempertanyakan',
 'mempunyai',
 'memulai',
 'memungkinkan',
 'menaiki',
 'menambahkan',
 'menandaskan',
 'menanti',
 'menanti-nanti',
 'menantikan',
 'menanya',
 'menanyai',
 'menanyakan',
 'mendapat',
 'mendapatkan',
 'mendatang',
 'mendatangi',
 'mendatangkan',
 'menegaskan',
 'mengakhiri',
 'mengapa',
 'mengatakan',
 'mengatakannya',
 'mengenai',
 'mengerjakan',
 'mengetahui',
 'menggunakan',
 'menghendaki',
 'mengibaratkan',
 'mengibaratkannya',
 'mengingat',
 'mengingatkan',
 'menginginkan',
 'mengira',
 'mengucapkan',
 'mengucapkannya',
 'mengungkapkan',
 'menjadi',
 'menjawab',
 'menjelaskan',
 'menuju',
 'menunjuk',
 'menunjuki',
 'menunjukkan',
 'menunjuknya',
 'menurut',
 'menuturkan',
 'menyampaikan',
 'menyangkut',
 'menyatakan',
 'menyebutkan',
 'menyeluruh',
 'menyiapkan',
 'merasa',
 'mereka',
 'merekalah',
 'merupakan',
 'meski',
 'meskipun',
 'meyakini',
 'meyakinkan',
 'minta',
 'mirip',
 'misal',
 'misalkan',
 'misalnya',
 'mula',
 'mulai',
 'mulailah',
 'mulanya',
 'mungkin',
 'mungkinkah',
 'nah',
 'naik',
 'namun',
 'nanti',
 'nantinya',
 'nyaris',
 'nyatanya',
 'oleh',
 'olehnya',
 'pada',
 'padahal',
 'padanya',
 'pak',
 'paling',
 'panjang',
 'pantas',
 'para',
 'pasti',
 'pastilah',
 'penting',
 'pentingnya',
 'per',
 'percuma',
 'perlu',
 'perlukah',
 'perlunya',
 'pernah',
 'persoalan',
 'pertama',
 'pertama-tama',
 'pertanyaan',
 'pertanyakan',
 'pihak',
 'pihaknya',
 'pukul',
 'pula',
 'pun',
 'punya',
 'rasa',
 'rasanya',
 'rata',
 'rupanya',
 'saat',
 'saatnya',
 'saja',
 'sajalah',
 'saling',
 'sama',
 'sama-sama',
 'sambil',
 'sampai',
 'sampai-sampai',
 'sampaikan',
 'sana',
 'sangat',
 'sangatlah',
 'satu',
 'saya',
 'sayalah',
 'se',
 'sebab',
 'sebabnya',
 'sebagai',
 'sebagaimana',
 'sebagainya',
 'sebagian',
 'sebaik',
 'sebaik-baiknya',
 'sebaiknya',
 'sebaliknya',
 'sebanyak',
 'sebegini',
 'sebegitu',
 'sebelum',
 'sebelumnya',
 'sebenarnya',
 'seberapa',
 'sebesar',
 'sebetulnya',
 'sebisanya',
 'sebuah',
 'sebut',
 'sebutlah',
 'sebutnya',
 'secara',
 'secukupnya',
 'sedang',
 'sedangkan',
 'sedemikian',
 'sedikit',
 'sedikitnya',
 'seenaknya',
 'segala',
 'segalanya',
 'segera',
 'seharusnya',
 'sehingga',
 'seingat',
 'sejak',
 'sejauh',
 'sejenak',
 'sejumlah',
 'sekadar',
 'sekadarnya',
 'sekali',
 'sekali-kali',
 'sekalian',
 'sekaligus',
 'sekalipun',
 'sekarang',
 'sekarang',
 'sekecil',
 'seketika',
 'sekiranya',
 'sekitar',
 'sekitarnya',
 'sekurang-kurangnya',
 'sekurangnya',
 'sela',
 'selain',
 'selaku',
 'selalu',
 'selama',
 'selama-lamanya',
 'selamanya',
 'selanjutnya',
 'seluruh',
 'seluruhnya',
 'semacam',
 'semakin',
 'semampu',
 'semampunya',
 'semasa',
 'semasih',
 'semata',
 'semata-mata',
 'semaunya',
 'sementara',
 'semisal',
 'semisalnya',
 'sempat',
 'semua',
 'semuanya',
 'semula',
 'sendiri',
 'sendirian',
 'sendirinya',
 'seolah',
 'seolah-olah',
 'seorang',
 'sepanjang',
 'sepantasnya',
 'sepantasnyalah',
 'seperlunya',
 'seperti',
 'sepertinya',
 'sepihak',
 'sering',
 'seringnya',
 'serta',
 'serupa',
 'sesaat',
 'sesama',
 'sesampai',
 'sesegera',
 'sesekali',
 'seseorang',
 'sesuatu',
 'sesuatunya',
 'sesudah',
 'sesudahnya',
 'setelah',
 'setempat',
 'setengah',
 'seterusnya',
 'setiap',
 'setiba',
 'setibanya',
 'setidak-tidaknya',
 'setidaknya',
 'setinggi',
 'seusai',
 'sewaktu',
 'siap',
 'siapa',
 'siapakah',
 'siapapun',
 'sini',
 'sinilah',
 'soal',
 'soalnya',
 'suatu',
 'sudah',
 'sudahkah',
 'sudahlah',
 'supaya',
 'tadi',
 'tadinya',
 'tahu',
 'tahun',
 'tak',
 'tambah',
 'tambahnya',
 'tampak',
 'tampaknya',
 'tandas',
 'tandasnya',
 'tanpa',
 'tanya',
 'tanyakan',
 'tanyanya',
 'tapi',
 'tegas',
 'tegasnya',
 'telah',
 'tempat',
 'tengah',
 'tentang',
 'tentu',
 'tentulah',
 'tentunya',
 'tepat',
 'terakhir',
 'terasa',
 'terbanyak',
 'terdahulu',
 'terdapat',
 'terdiri',
 'terhadap',
 'terhadapnya',
 'teringat',
 'teringat-ingat',
 'terjadi',
 'terjadilah',
 'terjadinya',
 'terkira',
 'terlalu',
 'terlebih',
 'terlihat',
 'termasuk',
 'ternyata',
 'tersampaikan',
 'tersebut',
 'tersebutlah',
 'tertentu',
 'tertuju',
 'terus',
 'terutama',
 'tetap',
 'tetapi',
 'tiap',
 'tiba',
 'tiba-tiba',
 'tidak',
 'tidakkah',
 'tidaklah',
 'tiga',
 'tinggi',
 'toh',
 'tunjuk',
 'turut',
 'tutur',
 'tuturnya',
 'ucap',
 'ucapnya',
 'ujar',
 'ujarnya',
 'umum',
 'umumnya',
 'ungkap',
 'ungkapnya',
 'untuk',
 'usah',
 'usai',
 'waduh',
 'wah',
 'wahai',
 'waktu',
 'waktunya',
 'walau',
 'walaupun',
 'wong',
 'yaitu',
 'yakin',
 'yakni',
 'yang']

In [25]:
tokens3 = [i for i in tokens2 if i not in stopwords.words('indonesian')]

In [26]:
tokens3

['halo',
 'selamat',
 'malam',
 'nama',
 'andre',
 'makan',
 'mie',
 'ayam',
 'harganya',
 'rp']

In [ ]:
Teknik Base :
    Normalisasi
    Tokenisasi
Teknik Advance :
    - Stemming
    - Lematization

## Bag of Words / Term Frequency (TF)

In [27]:
import pandas as pd
import numpy as np

In [28]:
text = [
'Ini adalah pensil, tapi itu adalah pulpen',
'Itu adalah pulpen.',
'Saya mau beli pulpen',
'Saya ada pulpen itu, tapi tidak ada pensil itu.',
'Saya tidak ada pensil ini.',
'Saya mau beli pulpen dan pensil',
'Ini adalah pulpen']

In [ ]:
## Vocabulary Building
Vocab = 
Ini,
adalah,
pensil,
tapi,
itu,
pulpen,
saya,
mau,
beli,
ada,
tidak,
dst

In [29]:
from sklearn.feature_extraction.text import CountVectorizer

In [30]:
bow = CountVectorizer()

In [31]:
bow_matrix = bow.fit_transform(text)

In [33]:
bow_matrix.toarray()

array([[0, 2, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0],
       [2, 0, 0, 0, 0, 2, 0, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]], dtype=int64)

In [35]:
bow.get_feature_names_out()

array(['ada', 'adalah', 'beli', 'dan', 'ini', 'itu', 'mau', 'pensil',
       'pulpen', 'saya', 'tapi', 'tidak'], dtype=object)

In [36]:
pd.DataFrame(bow_matrix.toarray(), columns= bow.get_feature_names_out(), index=text)

,ada,adalah,beli,dan,ini,itu,mau,pensil,pulpen,saya,tapi,tidak
"Ini adalah pensil, tapi itu adalah pulpen",0,2,0,0,1,1,0,1,1,0,1,0
Itu adalah pulpen.,0,1,0,0,0,1,0,0,1,0,0,0
Saya mau beli pulpen,0,0,1,0,0,0,1,0,1,1,0,0
"Saya ada pulpen itu, tapi tidak ada pensil itu.",2,0,0,0,0,2,0,1,1,1,1,1
Saya tidak ada pensil ini.,1,0,0,0,1,0,0,1,0,1,0,1
Saya mau beli pulpen dan pensil,0,0,1,1,0,0,1,1,1,1,0,0
Ini adalah pulpen,0,1,0,0,1,0,0,0,1,0,0,0

In [37]:
## Inverse Doucment Frequency

In [ ]:
ada = 3/ 7 ==> Kemunculan/seluruh dokumen
adalah = 4/7

In [38]:
# pada praktiknya akan digunakan Logaritmik terhadap IDF
## ditambah 1 untuk smoothing

## Term Frequency - Inverse Document Frequency

In [ ]:
TFIDF = BoW * idf  ==> efeknya mirip dg feature scalling untuk BoW agar yg terlalu sering muncul dianggap tidakj penting, contohnya Stopword

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [40]:
tfidf = TfidfVectorizer()

In [42]:
tfidf_matrix = tfidf.fit_transform(text)

In [43]:
pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf.get_feature_names_out(), index=text)

,ada,adalah,beli,dan,ini,itu,mau,pensil,pulpen,saya,tapi,tidak
"Ini adalah pensil, tapi itu adalah pulpen",0.000000,0.683160,0.000000,0.000000,0.341580,0.341580,0.000000,0.296562,0.228682,0.000000,0.399618,0.000000
Itu adalah pulpen.,0.000000,0.639111,0.000000,0.000000,0.000000,0.639111,0.000000,0.000000,0.427873,0.000000,0.000000,0.000000
Saya mau beli pulpen,0.000000,0.000000,0.589439,0.000000,0.000000,0.000000,0.589439,0.000000,0.337307,0.437432,0.000000,0.000000
"Saya ada pulpen itu, tapi tidak ada pensil itu.",0.621626,0.000000,0.000000,0.000000,0.000000,0.531346,0.000000,0.230659,0.177863,0.230659,0.310813,0.310813
Saya tidak ada pensil ini.,0.510836,0.000000,0.000000,0.000000,0.436646,0.000000,0.000000,0.379099,0.000000,0.379099,0.000000,0.510836
Saya mau beli pulpen dan pensil,0.000000,0.000000,0.452668,0.545327,0.000000,0.000000,0.452668,0.335932,0.259040,0.335932,0.000000,0.000000
Ini adalah pulpen,0.000000,0.639111,0.000000,0.000000,0.639111,0.000000,0.000000,0.000000,0.427873,0.000000,0.000000,0.000000

In [ ]:
N-Grams
- Agar kata yg lebih dari 1 bisa diperhatikan (frase)
- Contohnya : Pensil dan Kotak pensil adalah dua hal berbeda
- Diberlakukan sesuai urutan
- Sehinggan Token - Vocab tidak hanya berasal dari 1 suku kata

In [ ]:
Kotak Pensil ==> Kotak - Pensil

In [ ]:
- Saya membeli kotak pensil 1
- Saya meletakkan pensil di sebelah kotak 2
Jika menggunakan n-grams 1 kata, kotak dan pensil di sentence 1 dan 2 akan punya bobot yg sama, padahal memiliki arti yg berbeda

'Saya sedang makan nasi goreng pedas'

n gram 1 = saya, sedang, makan, nasi, goreng, pedas
n gram 2 = saya sedang, sedang makan, makan nasi, nasi goreng, goreng pedas
n gram 3 = saya sedang makan, sedang makan nasi, makan nasi goreng, nasi goreng pedas

In [44]:
tfidf_2 = TfidfVectorizer(ngram_range=(1,3)) ## berarti menggunakan ngram 1 sampai dg ngram 3

In [45]:
tfidf_matrix = tfidf_2.fit_transform(text)

In [47]:
tfidf_matrix.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.38082262, 0.26836263, 0.26836263, 0.19041131,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.19041131, 0.22276403, 0.26836263, 0.        , 0.19041131,
        0.22276403, 0.22276403, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.16531659, 0.        , 0.        ,
        0.26836263, 0.26836263, 0.12747693, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.22276403,
        0.26836263, 0.26836263, 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.40207741, 0.        , 0.        , 0.40207741,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.40207741,
        0.47039425, 0.47039425, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.26918355, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.3562758 , 0.3562758 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.3562758 ,
        0.3562758 , 0.3562758 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.20387916, 0.        , 0.        ,
        0.        , 0.        , 0.26439771, 0.        , 0.        ,
        0.3562758 , 0.3562758 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.36056869, 0.18028434, 0.        , 0.21718758, 0.21718758,
        0.21718758, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.30820216,
        0.        , 0.        , 0.21718758, 0.21718758, 0.        ,
        0.        , 0.        , 0.13379176, 0.        , 0.21718758,
        0.        , 0.        , 0.10316788, 0.        , 0.        ,
        0.21718758, 0.21718758, 0.13379176, 0.21718758, 0.21718758,
        0.        , 0.        , 0.        , 0.        , 0.18028434,
        0.        , 0.        , 0.21718758, 0.21718758, 0.18028434,
        0.18028434, 0.18028434],
       [0.28130254, 0.28130254, 0.33888366, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.24044809, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.20875891, 0.33888366, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.20875891, 0.        , 0.        ,
        0.        , 0.        , 0.33888366, 0.33888366, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.28130254,
        0.28130254, 0.28130254],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.25249477, 0.25249477, 0.30417909, 0.30417909, 0.30417909,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.25249477,
        0.25249477, 0.25249477, 0.18738022, 0.        , 0.        ,
        0.        , 0.        , 0.14449037, 0.30417909, 0.30417909,
        0.        , 0.        , 0.18738022, 0.        , 0.        ,
        0.25249477, 0.25249477, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.38339067, 0.        , 0.        , 0.38339067,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.38339067, 0.44853245, 0.        , 0.54034464, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.25667312, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])